= http-resource
:toc:
:toc-placement!:
\ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
\endif::[]

image::https://img.shields.io/docker/pulls/jgriff/http-resource[]

A Concourse https://resource-types.concourse-ci.org/[resource] for interacting with HTTP REST APIs.

toc::[]

[#config-source]
== Source Configuration

* `url`: _Required_. The HTTP URL, e.g. `"https://some-server:8080/some/endpoint"`.
* `username`: _Optional_. Username for accessing an authenticated url.
* `password`: _Optional_. Password for accessing an authenticated url.
* `insecure`: _Optional_. Set to `true` to ignore SSL errors.  Defaults to `false`.
* `method`: _Optional_. HTTP method to use.  When not specified here, this defaults to `GET` for `in` and `POST` for `out`.  Can also be overridden as a param to each `get` or `put` step.
* `headers`: _Optional_. Map of HTTP headers to include in the invocation.  Defaults to empty (none).  Additional headers can be specified as a params to each `get` or `put` step.
+
[source,yaml]
----
source:
  headers:
    Accept: application/json
----
* `file`: _Optional._ File containing content to be sent as the body of the request.  Cannot be specified at the same time as `text`.  Can be overridden as a parm to each `get` or `put` step.
* `text`: _Optional._ Inline text to be sent as the body of the request.  Cannot be specified at the same time as `file`.  Can be overridden as a parm to each `get` or `put` step.
+
TIP: Concourse https://concourse-ci.org/implementing-resource-types.html#resource-metadata[build metadata variables] can be used in both `file` and `text` content, and will be automatically substituted in `get` and `put` steps.

[#config-source-version]
* `version`: _Optional_. How to determine the resource's version (see xref:versions[]).  Default is to compute a hash digest of the response body (without the headers).

** `jq`: A `jq` expression to select a value from the response body as the version.
+
[source,yaml]
----
source:
  version:
    jq: .some.path.in.the.response.body
----
** `header`: A response header to use as the version.
+
[source,yaml]
----
source:
  version:
    header: Last-Modified
----
** `hash`: Compute a digest from a particular component of the response.  Options are:
*** `headers` - Compute the digest from the response headers only.
*** `body` - Compute the digest from the response body only.
*** `full` - Compute the digest from the response headers and body together.
+
[source,yaml]
----
source:
  version:
    hash: body
----
** `default`: The default version strategy to fall back on if none of the above are configured or cannot yield a non-empty value.
Options are:
*** `hash` - (Default) Compute a hash digest of the response body.
*** `none` - Don't emit any version.  Concourse will ignore the `check` result.

* `out_only`: _Optional._  Disables the `check` and `in` operations, turning them into no-ops (including the implicit `get` after each `put`).
Relevant for scenarios where you are _only_ using `put` operations, or for any other reason you do not want to regularly check the endpoint.  Default is `false`.
* `sensitive`: _Optional._  If `true`, the responses from the endpoint will be considered sensitive and not show up in the logs or Concourse UI.  Can be overridden as a param to each `get` or `put` step. Default is `false`.

== Behavior

=== `check`: Check for new resource version

Invokes the `url` and determines the current version according to the source `version` configuration.

NOTE: No-op if source param `out_only` is `true`.

=== `in`:  Invoke the `url`, capturing the response

Invokes the `url` and:

* writes the response headers to a file named `headers`.
* writes the response body to a file named `body`.

NOTE: No-op if source param `out_only` is `true`.

==== Parameters

* `strict`: _Optional._  Whether to strictly assert the version retrieved matches the version requested (from `check`).  Defaults to `false`.  If set to `true` and the versions to do not match, the step will fail.
+
TIP: Not all endpoints may be able to provide an idempotent version, this configuration lets you decide how you want to handle those scenarios.


=== `out`: Invoke the `url`, (optionally) sending a payload body

General purpose invocation of the `url`, optionally sending a request body.

[source,yaml]
----
  plan:
    - put: my-http-resource
      params:
        text: |
          The build had a result. Check it out at:
          $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          $ATC_EXTERNAL_URL/builds/$BUILD_ID
----

== Examples

=== `get` a resource

Issue `GET` requests to https://httpbin.org/get, and display the response `headers` and `body` we get back.

[source,yaml]
----
resource_types:
  - name: http-resource
    type: docker-image
    source:
      repository: jgriff/http-resource

resources:
  - name: http-bin
    type: http-resource
    source:
      url: https://httpbin.org/get

jobs:
  - name: get-something
    plan:
      - get: http-bin
        trigger: true
      - task: take-a-look
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          inputs:
            - name: http-bin
          run:
            path: cat
            args: ["http-bin/headers", "http-bin/body"]
----

=== `get` and `put`

`GET` a file, and `POST` it to another endpoint.

[source,yaml]
----
resource_types:
  - name: http-resource
    type: docker-image
    source:
      repository: jgriff/http-resource

resources:
  - name: http-bin-get
    type: http-resource
    source:
      url: https://httpbin.org/get
  - name: http-bin-post
    type: http-resource
    source:
      url: https://httpbin.org/post
      out_only: true                  <2>

jobs:
  - name: post-something
    plan:
      - get: http-bin-get
        trigger: true
      - put: http-bin-post
        params:
          file: http-bin-get/body     <1>
----
<1> post the file content that was retrieved in the `get` step.
<2> disable the implicit `get` after a `put` (since issuing a `GET` to `https://httpbin.org/post` returns a `405 METHOD NOT ALLOWED` and will fail our pipeline).

=== `get` ignore some versions

In some scenarios, you may want to version on a response property or header that may not always be returned.

The default behavior for this would be to fallback to generating a `hash` of the response payload.
However, if you would rather simply skip those missing versions all together, you can configure the `default` to `none`.
This will cause `check` to omit that version.

For example, if we want to version _only_ on responses that contain the structure:

[source,json]
----
{
  "usually": {
    "present": {
      "version": "some-version-value"
    }
  }
}
----

Then we can configure our pipeline as:

[source,yaml]
----
resource_types:
  - name: http-resource
    type: docker-image
    source:
      repository: jgriff/http-resource

resources:
  - name: volatile-endpoint
    type: http-resource
    source:
      url: https://someplace.io/anything
      version:
        jq: .usually.present.version  <1>
        default: none                 <2>

jobs:
  - name: get-good-version
    plan:
      - get: volatile-endpoint
        strict: true                  <3>
        trigger: true
----
<1> for versions we want, this attribute will be present in the response body.
<2> ignores any response without our desired `jq` path
<3> ensure we only process resource versions that strictly match our version requirements.

This also works nicely in fallback strategies.

[source,yaml]
----
    source:
      url: https://someplace.io/anything
      version:
        jq: .usually.present.version  <1>
        header: Might-Exist           <2>
        default: none                 <3>
----
<1> Try a `jq` query first.
<2> If that doesn't match, check for a response header.
<3> If neither of those match, then ignore the version.

For more details, see xref:versions[].

[#versions]
== Version Strategies

By default, a hash digest of the response body is used as the version of the resource.

However, you can configure any/all of the xref:config-source-version[`version`] strategies together and they will be attempted in the following order:

. `jq`
. `header`
. `hash`
. `default`

The first one to yield a non-empty value will be used as the version.

If none of them can produce a non-empty string, then the configured `default` strategy is used (which defaults to a `hash` of the response body).

For example, suppose our endpoint returns the following response:

[source]
----
HTTP/1.1 200 OK
Content-Type: application/json
Some-Header: some-header-value
Version: 1

{
  "some": "response",
  "version": "abc-123"
}
----

The table below lists various examples for determining the version from this endpoint.

.Version Examples
[cols="a,a"]
|===
|Source Config |Yields

|[source,yaml]
----
    source:
      version:
        jq: .version
----
|`"abc-123"`

|[source,yaml]
----
    source:
      version:
        header: Version
----
|`1`

|[source,yaml]
----
    source: # no version config
----
or
[source,yaml]
----
    source:
      version:
        hash: body
----
or
[source,yaml]
----
    source:
      version:
        default: hash
----
|(hash of response body)

|[source,yaml]
----
    source:
      version:
        hash: headers
----
|(hash of response headers)

|[source,yaml]
----
    source:
      version:
        hash: full
----
|(hash of response headers + body)

|===

.Version Examples - Fallback Scenarios
[cols="a,a"]
|===
|Source Config |Yields

|[source,yaml]
----
    source:
      version:
        jq: .version            # value
        header: Version         # not tried
----
|`"abc-123"`

|[source,yaml]
----
    source:
      version:
        jq: .does.not.exist     # no value
        header: Version         # value
----
|`1`

|[source,yaml]
----
    source:
      version:
        jq: .does.not.exist     # no value
        header: Does-Not-Exist  # no value
        # none match, defaults to hash
----
or
[source,yaml]
----
    source:
      version:
        jq: .does.not.exist     # no value
        header: Does-Not-Exist  # no value
        hash: body              # value
----
or
[source,yaml]
----
    source:
      version:
        jq: .does.not.exist     # no value
        header: Does-Not-Exist  # no value
        default: hash           # default to hash
----
|(hash of response body)

|[source,yaml]
----
    source:
      version:
        jq: .does.not.exist     # no value
        header: Does-Not-Exist  # no value
        default: none           # default to no version
----
|Yields no versions.  Concourse will ignore the result of `check`.

|===

[WARNING]
====
Configuring the `version` with _only_ a `default` of `none` will _never_ yield _any_ version from `check`.

[source,yaml]
----
    source:
      version:
        default: none
----
====
