#!/bin/bash

set -e

exec 5>&1 # make stdout available as fd 5 for the result
exec 1>&2 # redirect all output to stderr for logging

main() {
  log "\n\n--[CHECK]-------------------------"
  exitIfNoop
  checkResource
  emitResult
}

exitIfNoop() {
  if isTrue source_out_only; then
    log -p "\n${gray}--> no-op (source config 'out_only' is true)${reset}"
    jq  -n '[]' >&5
    exit 0
  fi
}

checkResource() {
  set -o pipefail
  log -p "\n--> checking resource ..."
  invokeEndpoint
}

emitResult() {
  out=$(jq -n --arg version "$version" '[{version: $version}]')
  log "\n--> OUT\n$out"
  jq -n "$out" | jq 'flatten' >&5
}

if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
  source $(dirname $0)/common
  source $(dirname $0)/curlops
  main "$@"
fi
