#!/bin/bash

set -e

exec 5>&1 # make stdout available as fd 5 for the result
exec 1>&2 # redirect all output to stderr for logging

main() {
  log "\n\n--[OUT]-------------------------"
  sourcesDirectory $1
  putResource
  emitResult
}

sourcesDirectory() {
  sources_dir=$1
  log "\n--> sources directory is: $sources_dir"
  cd $sources_dir
}

putResource() {
  log -p "\n--> put'ing resource ..."
  default_method=POST
  invokeEndpoint
}

emitResult() {
  jq  --arg version "$version" \
      --arg method "$method" \
      --arg url "$source_url" \
      --arg status "$response_status" \
      -n '{
    "version": {
      "version": $version
    },
    "metadata": [
      { "name": "method", "value": $method },
      { "name": "url", "value": $url },
      { "name": "status", "value": $status }
    ]
  }' >&5
}

if [ "${BASH_SOURCE[0]}" == "${0}" ]; then
  source $(dirname $0)/common
  source $(dirname $0)/curlops
  main "$@"
fi
